import { createClient } from '@supabase/supabase-js';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SUPABASE_URL = process.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('Error: Missing Supabase environment variables');
  console.log('Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your .env file');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

async function generateTypes() {
  try {
    const { data, error } = await supabase.rpc('get_types', {});
    
    if (error) {
      console.error('Error generating types:', error);
      return;
    }

    const typesPath = join(__dirname, '../src/integrations/supabase/types.ts');
    
    // Format the types with a proper header
    const typesContent = `/**
 * This file was auto-generated by the Supabase CLI.
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Instead, run \`npm run generate:types\` to regenerate it.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

${data.types}`;

    writeFileSync(typesPath, typesContent);
    console.log('Types generated successfully!');
  } catch (error) {
    console.error('Failed to generate types:', error);
  }
}

generateTypes();
