import { createClient } from '@supabase/supabase-js';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || 'https://tbhecgdnkzkaevqxscdc.supabase.co';
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_ANON_KEY) {
  console.error('Error: Missing Supabase anon key');
  console.log('Please set VITE_SUPABASE_ANON_KEY in your .env file');
  process.exit(1);
}

async function main() {
  const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
  
  try {
    // Récupérer les types générés par Supabase
    const { data: types, error } = await supabase.rpc('get_types');
    
    if (error) {
      console.error('Error fetching types:', error);
      return;
    }

    if (!types) {
      console.log('No types returned from the database');
      return;
    }

    const typesPath = join(__dirname, '../src/integrations/supabase/types.ts');
    const content = `/**
 * This file is auto-generated by Supabase.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

${types}`;

    writeFileSync(typesPath, content);
    console.log('Types updated successfully!');
  } catch (err) {
    console.error('Failed to update types:', err);
  }
}

main();
